In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv("googleplaystore.csv")

In [2]:
df.head()
df.columns.str.strip()

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [4]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [5]:
df['Installs'] = df['Installs'].str.replace('+', '').str.replace(',', '', regex=True)
df['Size'] = df['Size'].str.replace('M', '', regex=True)

C:\Users\Dell\AppData\Local\Temp\ipykernel_9188\3434813835.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Installs'] = df['Installs'].str.replace('+', '').str.replace(',', '', regex=True)

In [6]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19,10000,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25,50000000,Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53,5000,Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6,100,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5,1000,Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,1000,Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19,10000000,Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [7]:
df['Rating']=pd.to_numeric(df['Rating'],errors='coerce')
df['Reviews']=pd.to_numeric(df['Reviews'],errors='coerce').astype('Int64')
df['Size']=pd.to_numeric(df['Size'],errors='coerce')
df['Installs']=pd.to_numeric(df['Installs'],errors='coerce').astype('Int64')
df['Price']=pd.to_numeric(df['Price'],errors='coerce')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10840 non-null  Int64
 4   Size            8829 non-null   float64
 5   Installs        10840 non-null  Int64
 6   Type            10840 non-null  object
 7   Price           10040 non-null  float64
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: Int64(2), float64(3), object(8)
memory usage: 1.1+ MB

In [9]:
df['App'] = df['App'].str.lower()
df['Category'] = df['Category'].str.lower()
df['Type'] = df['Type'].str.lower()
df['Content Rating'] = df['Content Rating'].str.lower()
df['Genres'] = df['Genres'].str.lower()

In [10]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,photo editor & candy camera & grid & scrapbook,art_and_design,4.1,159,19.0,10000,free,0.0,everyone,art & design,"January 7, 2018",1.0.0,4.0.3 and up
1,coloring book moana,art_and_design,3.9,967,14.0,500000,free,0.0,everyone,art & design;pretend play,"January 15, 2018",2.0.0,4.0.3 and up
2,"u launcher lite – free live cool themes, hide ...",art_and_design,4.7,87510,8.7,5000000,free,0.0,everyone,art & design,"August 1, 2018",1.2.4,4.0.3 and up
3,sketch - draw & paint,art_and_design,4.5,215644,25.0,50000000,free,0.0,teen,art & design,"June 8, 2018",Varies with device,4.2 and up
4,pixel draw - number art coloring book,art_and_design,4.3,967,2.8,100000,free,0.0,everyone,art & design;creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,sya9a maroc - fr,family,4.5,38,53.0,5000,free,0.0,everyone,education,"July 25, 2017",1.48,4.1 and up
10837,fr. mike schmitz audio teachings,family,5.0,4,3.6,100,free,0.0,everyone,education,"July 6, 2018",1.0,4.1 and up
10838,parkinson exercices fr,medical,NaN,3,9.5,1000,free,0.0,everyone,medical,"January 20, 2017",1.0,2.2 and up
10839,the scp foundation db fr nn5n,books_and_reference,4.5,114,NaN,1000,free,0.0,mature 17+,books & reference,"January 19, 2015",Varies with device,Varies with device
10840,ihoroscope - 2018 daily horoscope & astrology,lifestyle,4.5,398307,19.0,10000000,free,0.0,everyone,lifestyle,"July 25, 2018",Varies with device,Varies with device

In [11]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              1
Size              2012
Installs             1
Type                 1
Price              801
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [12]:
df['Rating'] = df['Rating'].fillna(0)
df['Reviews'] = df['Reviews'].fillna(0)
df['Size'] = df['Size'].fillna(0)
df['Installs'] = df['Installs'].fillna(0)
df['Type'] = df['Type'].fillna("undefined")
df['Price'] = df['Price'].fillna(0)
df['Content Rating'] = df['Content Rating'].fillna("undefined")
df['Current Ver'] = df['Current Ver'].fillna("undefined")
df['Android Ver'] = df['Android Ver'].fillna("undefined")

In [13]:
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

In [14]:
df.drop_duplicates(keep=False, inplace=True)

In [15]:
df.duplicated().any()

False

# Q1. number of app titles contain astrology

In [16]:
df[df["App"].str.contains("astrology" , case = False)]["App"].count()

3

# Q2. which category getting the highest average rating ?

In [17]:
df.groupby("Category")[["Rating"]].mean()

                        Rating
Category
1.9                  19.000000
art_and_design        4.156923
auto_and_vehicles     3.598824
beauty                3.390566
books_and_reference   3.342358
business              2.471106
comics                4.016667
communication         3.436705
dating                3.099375
education             4.331532
entertainment         4.151765
events                3.118750
family                3.698279
finance               3.622034
food_and_drink        3.542149
game                  4.092987
health_and_fitness    3.558608
house_and_home        3.436111
libraries_and_demo    3.195294
lifestyle             3.333151
maps_and_navigation   3.667153
medical               2.994350
news_and_magazines    3.297590
parenting             3.583333
personalization       3.454805
photography           3.934295
productivity          3.411735
shopping              3.772362
social                3.680524
sports                3.391159
tools                 3.524081
travel_and_local      3.500000
video_players         3.715429
weather               3.881707

# Q3. find total number of apps having 5 star rating

In [18]:
df['Rating'] == 5.0

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837     True
10838    False
10839    False
10840    False
Name: Rating, Length: 9948, dtype: bool

In [19]:
df[df['Rating'] == 5.0].count()['App']

268

# Q4. find total number of free and paid app

In [20]:
df.groupby(['Type']).count()

,App,Category,Rating,Reviews,Size,Installs,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
Type,,,,,,,,,,,,
0,1,1,1,1,1,1,1,1,1,1,1,1
free,9215,9215,9215,9215,9215,9215,9215,9215,9215,9215,9215,9215
paid,731,731,731,731,731,731,731,731,731,731,731,731
undefined,1,1,1,1,1,1,1,1,1,1,1,1

# Q5. which app has maximum reviews?

In [21]:
df[['Reviews']].sort_values('Reviews',ascending = False)
df[df['Reviews'].max() == df['Reviews']][['App' , 'Reviews']]

           App   Reviews
2544  facebook  78158306

# Q6. display top 5 apps having highest review

In [22]:
df.sort_values(by=['Reviews'], ascending = False).head(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2544,facebook,social,4.1,78158306,0.0,1000000000,free,0.0,teen,social,"August 3, 2018",Varies with device,Varies with device
3943,facebook,social,4.1,78128208,0.0,1000000000,free,0.0,teen,social,"August 3, 2018",Varies with device,Varies with device
3904,whatsapp messenger,communication,4.4,69109672,0.0,1000000000,free,0.0,everyone,communication,"August 3, 2018",Varies with device,Varies with device
2604,instagram,social,4.5,66577446,0.0,1000000000,free,0.0,teen,social,"July 31, 2018",Varies with device,Varies with device
3909,instagram,social,4.5,66509917,0.0,1000000000,free,0.0,teen,social,"July 31, 2018",Varies with device,Varies with device

# Q7. find average rating of free and paid apps

In [23]:
df.groupby("Type")[["Rating"]].mean()

              Rating
Type
0          19.000000
free        3.587206
paid        3.376881
undefined   0.000000

# Q8. display top 5 apps having maximum install

In [24]:
df.sort_values(by=['Installs'], ascending = False).head(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
3896,subway surfers,game,4.5,27711703,76.0,1000000000,free,0.0,everyone 10+,arcade,"July 12, 2018",1.90.0,4.1 and up
3996,google chrome: fast & secure,communication,4.3,9642112,0.0,1000000000,free,0.0,everyone,communication,"August 1, 2018",Varies with device,Varies with device
3928,youtube,video_players,4.3,25623548,0.0,1000000000,free,0.0,teen,video players & editors,"August 2, 2018",Varies with device,Varies with device
3909,instagram,social,4.5,66509917,0.0,1000000000,free,0.0,teen,social,"July 31, 2018",Varies with device,Varies with device
3904,whatsapp messenger,communication,4.4,69109672,0.0,1000000000,free,0.0,everyone,communication,"August 3, 2018",Varies with device,Varies with device

# Q9. how many apps upload in 2018

In [30]:
df[df["Last Updated"].str.contains("2018" , case = False)]["App"].count()

6584

# Q10. how many apps in category game

In [31]:
df['Category'] == 'game'

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840    False
Name: Category, Length: 9948, dtype: bool

In [32]:
df[df['Category'] == 'game'].count()['App']

1098